import React, { useState } from 'react'
import Card from '../components/card'

import styles from '../App.scss'

export default function Cover() {
  return (
    <>
    <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>
      <div id="cell"></div>



      <div id="content">
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      <div id="cover-title">PokéMon For Everyone</div>
      </div>

    </>
  )
}
